kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbitmq-storage
  labels:
    app: rabbitmq
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  resources:
    requests:
      storage: 2Gi
