apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
  - name: amqp
    port: 5672
    nodePort: 30010
    targetPort: amqp
    protocol: TCP
  - name: management
    port: 15672
    nodePort: 30011
    targetPort: management
    protocol: TCP
  selector:
    app: rabbitmq
  type: NodePort
